language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -e . -r requirements-testing.txt django$DJANGO_VERSION
script:
  - django-admin.py test
  - coveralls
env:
  global:
    - DJANGO_SETTINGS_MODULE=simpleimages.test.settings
  matrix:
    - DJANGO_VERSION="==1.6a1"
    - DJANGO_VERSION=">=1.5,<1.6"
