language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -e .
  - pip install -r requirements-testing.txt
script:
  - django-admin.py test
  - coveralls
env:
  global:
    - DJANGO_SETTINGS_MODULE=simpleimages.test.settings
