language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
services:
  - redis-server
install:
  - pip install -e . -r requirements-testing.txt $DJANGO_VERSION
script:
  - py.test
after_success:
  - coveralls
env:
  global:
    - DB_HOST=localhost
    - REDIS_HOST=localhost
  matrix:
    - DJANGO_VERSION="django>=1.8,<1.9"
    - DJANGO_VERSION="django>=1.7,<1.8"
    - DJANGO_VERSION="django>=1.6,<1.7"
    - DJANGO_VERSION="django>=1.5,<1.6"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.7,<1.8"
