language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -q -e .
  - pip install -q --use-mirrors -r requirements-testing.txt
script:
  - django-admin.py test
  - coveralls
env:
  global:
    - DJANGO_SETTINGS_MODULE=simpleimages.test.settings
  matrix:
    - USE_CACHE=true
    - USE_CACHE=
