language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
# command to run tests
script:
  - django-mini.py -a simpleimages --test-runner 'discover_runner.DiscoverRunner' test
