language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -q -e .
  - pip install -q --use-mirrors -r requirements-testing.txt
script:
  - coverage run --branch --source=simpleimages -m django-mini -a simpleimages -a simpleimages.test --test-runner 'discover_runner.DiscoverRunner' test
  - coveralls
