language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
install:
  - pip install -e . -r requirements-testing.txt $DJANGO_VERSION
script:
  - django-admin.py test
after_success:
  - coveralls
env:
  global:
    - DJANGO_SETTINGS_MODULE=simpleimages.test.settings
  matrix:
    - DJANGO_VERSION="https://www.djangoproject.com/download/1.6b1/tarball/"
    - DJANGO_VERSION="django>=1.5,<1.6"
