language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
services:
  - redis-server
before_script:
  - psql -c 'create database django_simpleimages;' -U postgres
install:
  - pip install -e . -r requirements-testing.txt $DJANGO_VERSION
script:
  - py.test
after_success:
  - coveralls
env:
  matrix:
    - DJANGO_VERSION="django>=1.5,<1.6"
    - DJANGO_VERSION="django>=1.6,<1.7"
