language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -r requirements-testing.txt
  - pip install -U django$DJANGO_VERSION
script:
  - make test
  - coveralls
env:
  - DJANGO_VERSION=">=1.1,<1.2"
  - DJANGO_VERSION=">=1.2,<1.3"
  - DJANGO_VERSION=">=1.3,<1.4"
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION=">=1.5,<1.6"
